version: '3'
networks:
  dsnet:
services:
  ds-catalog-db:
    container_name: ds-catalog-db
    image: postgres:10.5-alpine
    restart: always
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_DB=products
      - POSTGRES_PASSWORD=pr0duct
      - POSTGRES_USER=develop
    networks:
      - dsnet
  ds-catalog-api:
    container_name: ds-catalog-api
    depends_on:
      - ds-catalog-db
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:postgresql://ds-catalog-db:5432/products
      - spring.datasource.username=develop
      - spring.datasource.password=pr0duct
      - spring.profiles.active=dev
      - opentracing.jaeger.udp-sender.host=jaeger
#      - opentracing.jaeger.udp-sender.port=6831
    ports:
      - "3000:8080"
    networks:
      - dsnet
  jaeger:
    image: jaegertracing/all-in-one:1.25
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - dsnet